Parallel sle
n0n1ck1/linalg_lib pull request #17
Opened 2021-07-27 18:50 UTC by AnyaAkhmatova

Попробовала реализовать параллельное решение СЛУ. Решение находится только если оно единственно, иначе выкидывается Matrix<T>(0,0) - пустая матрица, ее можно проверять с помощью empty(). Реализации две. Первая - parallel_sle_solution_similar_simple, она похожа на реализации нахождения определителя и обратной матрицы. Вторая - parallel_sle_solution_per_rows - распараллеливает по строкам, каждая нить работает со своей строкой. Также написала простенькие тесты. Кое-где добавила комменты, либо с вопросом стоит ли распараллеливать, либо с проблемами, которые сама еще не решила.

2021-07-27 19:07 UTC, n0n1ck1 commented on matrix/matrix.h
> +        if (std::abs(matrix_[i*width_ + j] - other.matrix_[i*width_ + j]) >= eps) {
Макс написал, что лучше использовать относительную погрешность, думаю, что 1е-5 будет норм

2021-07-27 19:08 UTC, n0n1ck1 commented on matrix/functions.h
> +Matrix<T> operator+(const Matrix<T>& matrix1, const Matrix<T>& matrix2) { //стоит ли здесь тоже оставить 2 нити, как в dot?
Да, думаю, что во всех операторах можно поставить n_threads, как в dot

2021-07-27 19:10 UTC, n0n1ck1 requested changes
Позже ещё надо будет непараллельное решение закинуть в файл с непараллельными функциями

2021-07-28 17:39 UTC, AnyaAkhmatova commented on matrix/matrix.h
> +        if (std::abs(matrix_[i*width_ + j] - other.matrix_[i*width_ + j]) >= eps) {
Сделала

2021-07-28 17:39 UTC, AnyaAkhmatova commented on matrix/functions.h
> +Matrix<T> operator+(const Matrix<T>& matrix1, const Matrix<T>& matrix2) { //стоит ли здесь тоже оставить 2 нити, как в dot?
Сделала

2021-07-28 19:08 UTC, n0n1ck1 approved these changes

2021-07-29 12:17 UTC, thebensky approved these changes
сори, думал, достаточно, что стас подтвердил

2021-07-29 16:52 UTC, merged