Parallel rank
n0n1ck1/linalg_lib pull request #23
Opened 2021-08-02 13:28 UTC by AnyaAkhmatova

Добавлено:
-бенчмарки для СЛУ(параллельно и последовательно)
-бенчмарки для ранга(параллельно и последовательно)
-ранг параллельно(parallel_rank, parallel_rank_per_rows),
-ранг последовательно(seq_rank)
-тесты для ранга(параллельно и последовательно)
-немного поправила функции в functions.h (parallel_sle_solution)
-удалила sle_solution(последовательный) из functions.h (вопрос: стоит ли переименовать parallel_sle_solution и parallel_sle_solution_per_rows во что-нибудь покороче и без parallel?)

2021-08-02 13:39 UTC, thebensky commented on matrix/functions.h
> +size_t parallel_rank(const Matrix<T>& matrix) {
думаю, названия параллельных функций можно писать без parallel - получается длинно, кажется, легче сделать просто function и seq_function (как в остальных функциях)
так же и с sle_solution - мы ведь пишем библиотеку для параллельных вычислений, должно быть очевидно без приставки parallel

2021-08-02 15:06 UTC, thebensky commented on matrix/functions.h
> +size_t parallel_rank_per_rows(const Matrix<T>& matrix) {
кстати, я тут заметил - матрица передается по ссылке, а внутри копируется, притом оригинальная дальше никак не используется. это, конечно, не влияет на производительность - но для большей читаемости можно сразу копировать (то же самое, думаю, можно сделать и в других функциях)

2021-08-02 22:04 UTC, n0n1ck1 requested changes
Матвей дело говорит, остальное вроде норм

2021-08-03 15:34 UTC, AnyaAkhmatova commented on matrix/functions.h
> +size_t parallel_rank(const Matrix<T>& matrix) {
Сделала sle_solution, fast_sle_solution, seq_sle_solution, rank, fast_rank, seq_rank.

2021-08-03 15:42 UTC, thebensky approved these changes
ура! вообще без замечаний

2021-08-03 15:51 UTC, n0n1ck1 approved these changes

2021-08-03 18:48 UTC, merged